# Generated by Django 4.2.7 on 2025-08-30 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_groupmembership_manageduser_managedgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_controller', models.CharField(help_text='Endereço do Domain Controller', max_length=255)),
                ('domain_name', models.CharField(help_text='Nome do domínio AD', max_length=255)),
                ('base_dn', models.CharField(help_text='Base DN para pesquisas LDAP', max_length=500)),
                ('service_account_username', models.CharField(help_text='Usuário de serviço para conexão', max_length=255)),
                ('service_account_password', models.CharField(help_text='Senha do usuário de serviço', max_length=500)),
                ('sync_enabled', models.BooleanField(default=False)),
                ('sync_interval_minutes', models.PositiveIntegerField(default=60)),
                ('sync_users', models.BooleanField(default=True)),
                ('sync_groups', models.BooleanField(default=True)),
                ('users_ou', models.CharField(blank=True, help_text='OU dos usuários', max_length=500)),
                ('groups_ou', models.CharField(blank=True, help_text='OU dos grupos', max_length=500)),
                ('agent_status', models.CharField(choices=[('OFFLINE', 'Offline'), ('ONLINE', 'Online'), ('ERROR', 'Erro'), ('SYNCING', 'Sincronizando')], default='OFFLINE', max_length=20)),
                ('agent_last_seen', models.DateTimeField(blank=True, null=True)),
                ('agent_version', models.CharField(blank=True, max_length=50)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, choices=[('SUCCESS', 'Sucesso'), ('ERROR', 'Erro'), ('RUNNING', 'Executando')], max_length=20, null=True)),
                ('last_sync_message', models.TextField(blank=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad_config', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant__name'],
            },
        ),
    ]
